# Generated by Django 3.2.7 on 2022-01-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
